@startuml

skinparam monochrome true
skinparam classAttributeIconSize 0

together dataAndStatusGroup{
    class cData{
        +m_vGuestBook
        +bChangeState = true
        +nPreviousRandomNumber=1
    }

    class cStatus{
        +SetStatus()
        +SetStatusMessage()
        +GetStatus()
        +GetStatusMessage()
        -m_bExecutionStatus = true
        -m_spExecMessage
    }
}
class cStateMachine{
    -m_spData
    -m_spStatus
    -m_spActualState
    -m_spNextState
    -m_spState1
    -m_spState2
    -m_spState3
    -m_spState4
    +RunSTM()
}

class cState{
    #m_spData
    #m_spStatus
    #m_spPossibleNextStates
    #m_spNextState
    +AddPossibleNextStates()
    +ReturnNextState()
    {abstract}+ExecuteStateTask()
    +SetDataPointer()
    +SetStatusPointer()
}
class cState1{
    +ExecuteStateTask()
}
class cState2{
    +ExecuteStateTask()
}
class cState3{
    +ExecuteStateTask()
}
class cState4{
    +ExecuteStateTask()
}

cState <|-- cState1
cState <|-- cState2
cState <|-- cState3
cState <|-- cState4


cStateMachine *-- cState1
cStateMachine *-- cState2
cStateMachine *-- cState3
cStateMachine *-- cState4

cStateMachine ..> cState:<<uses>>

cData -[hidden]down- cStatus
cStateMachine o-- cData
cStateMachine o-- cStatus

cStateMachine -[hidden]right-- cData
cStateMachine -[hidden]right-- cStatus
@enduml
